import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import Sidebar from "./components/Sidebar";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Play Rune",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className='min-h-screen'>
          {/* Navigation (fixed) */}
          <Nav />
          
          {/* Content Container */}
          <Providers>
            <section className='flex w-[90%] mx-auto pt-5'>
              {/* Fixed Sidebar */}
              <div className='sticky top-[80px] h-[calc(100vh-80px)]'>
                <Sidebar />
              </div>
      
              {/* Main */}
              <div className="ml-10 w-[70vw]">
                {children}
              </div>
            </section>
          </Providers>
        </main>
      </body>
    </html>
  );
}