import type { Metadata } from "next";

import "./globals.css";
import Nav from "./components/Nav";
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "Play Rune",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
          <main className='min-h-screen'>
              {/* Navigation (fixed) */}
              <Nav />
              
              {/* Content Container */}
              <section className='flex w-[90%] mx-auto pt-5'>
                {/* Fixed Sidebar */}
                <div className='sticky top-[80px] h-[calc(100vh-80px)]'>
                  <Sidebar />
                </div>
        
                {/* Main  */}
                 {children}
              </section>
            </main>
       
      </body>
    </html>
  );
}
